/* NewTab — original, buildless application. All user text is rendered as text. */
(function(){
'use strict';
const C=NewTabCore,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const paths={settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M15.5 12a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',plus:'M12 5v14 M5 12h14',arrow:'M5 12h14 M13 6l6 6-6 6',chevron:'M9 5l7 7-7 7',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0 M12 6v6l4 2',calendar:'M4 5h16v16H4z M8 2v6 M16 2v6 M4 10h16',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M12 1v3 M12 20v3 M1 12h3 M20 12h3 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2',cloud:'M6 18a5 5 0 1 1 1-10 6 6 0 0 1 11 2 4 4 0 0 1 0 8z',rain:'M5 15a4 4 0 1 1 2-8 5 5 0 0 1 10 1 4 4 0 0 1 1 8 M7 18l-1 3 M12 17l-1 3 M17 18l-1 3',snow:'M12 2v20 M3 7l18 10 M3 17L21 7 M9 4l3 3 3-3 M9 20l3-3 3 3',image:'M3 3h18v18H3z M3 17l6-6 4 4 3-3 5 5 M17 7h.01',pages:'M7 3h14v14H7z M3 7v14h14',data:'M4 5c0-4 16-4 16 0s-16 4-16 0v14c0 4 16 4 16 0V5 M4 12c0 4 16 4 16 0',minus:'M5 12h14',grip:'M8 6h.01 M16 6h.01 M8 12h.01 M16 12h.01 M8 18h.01 M16 18h.01',resize:'M9 20h11V9 M5 5l15 15',edit:'M4 17L16 5l3 3L7 20H4z M14 7l3 3',folder:'M3 6h7l2 3h9v11H3z',undo:'M8 5L3 10l5 5 M3 10h10a7 7 0 0 1 7 7',location:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 1 1 14 0 M14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0'};
function icon(name){const ns='http://www.w3.org/2000/svg',s=document.createElementNS(ns,'svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');const p=document.createElementNS(ns,'path');p.setAttribute('d',paths[name]||paths.grid);s.append(p);return s}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function button(text,fn,cls='plain'){const n=el('button',cls,text);n.type='button';if(fn)n.addEventListener('click',fn);return n}
function actionIcon(name,label,fn,cls='round'){const n=button('',fn,cls);n.append(icon(name));n.setAttribute('aria-label',label);n.title=label;return n}
let bootMessage='',state=loadState(),editing=false,undoStack=[],drag=null,swipe=null,weatherData=null,weatherStale=false,weatherError='',weatherBusy=false,weatherRequest=0,timetableData=null,timetableStale=false,timetableError='',timetableBusy=false,manualDay=null,toastTimer=null,currentSection=null,wallpaperURL=null,folderId=null,suggestController=null;
function loadState(){try{let raw=localStorage.getItem(C.KEY);if(raw)return C.normalize(JSON.parse(raw));for(const key of ['homeGridStateV3','homeGridStateV2','pixelHomeStateV1']){raw=localStorage.getItem(key);if(raw){bootMessage='以前の設定を引き継ぎました。';return C.normalize(JSON.parse(raw))}}}catch{bootMessage='設定を読み込めなかったため初期配置を表示しています。元の保存データは残しています。'}return C.defaults()}
function persist(){try{localStorage.setItem(C.KEY,JSON.stringify(state));return true}catch{toast('保存できませんでした。設定を書き出してバックアップしてください。');return false}}
function readCache(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function writeCache(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{/* Cache failures must never block home. */}}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4200)}
function checkpoint(){undoStack.push(C.clone(state));if(undoStack.length>25)undoStack.shift();$('#undo').hidden=false}
function mutate(fn){checkpoint();fn();persist();render()}
function undo(){if(!undoStack.length)return;state=undoStack.pop();persist();render();$('#undo').hidden=!undoStack.length;toast('変更を元に戻しました。')}
const page=()=>state.pages.find(p=>p.id===state.activePage)||state.pages[0];
const effectiveCols=()=>innerWidth<760?Math.min(6,state.grid.columns):state.grid.columns;
function shownItems(p){return C.pack(p.items.filter(i=>!C.WIDGETS.includes(i.id)||state.widgets[i.id].enabled),effectiveCols(),state.grid.columns)}
function findShortcut(id){return state.shortcuts.find(s=>s.id===id)}
function findFolder(id){return state.folders.find(f=>f.id===id)}
function findItem(id){for(const p of state.pages){const item=p.items.find(i=>i.id===id);if(item)return{p,item}}return null}
function itemName(id){return C.LABELS[id]||(id.startsWith('s:')?findShortcut(id.slice(2))?.name:findFolder(id.slice(2))?.name)||'アイテム'}
function applyAppearance(){const a=state.appearance,r=document.documentElement;const themes={silver:{surface:'242,247,254',ink:'#182638',muted:'#526176',accent:'#1870db'},ocean:{surface:'220,240,252',ink:'#0a344a',muted:'#3e667b',accent:'#087cb1'},rose:{surface:'253,236,243',ink:'#4d243e',muted:'#805c73',accent:'#ba417a'},dark:{surface:'22,32,49',ink:'#f0f5fc',muted:'#b5c3d4',accent:'#89baff'}};let t=themes[a.theme];if(a.autoTheme&&a.palette)t={...themes[a.palette.dark?'dark':'silver'],accent:a.palette.accent};for(const k of ['surface','ink','muted','accent'])r.style.setProperty('--'+k,t[k]);r.style.colorScheme=(a.autoTheme&&a.palette?a.palette.dark:a.theme==='dark')?'dark':'light';r.style.setProperty('--label',a.autoTheme&&a.palette?a.palette.label:'#ffffff');r.style.setProperty('--alpha',a.opacity/100);r.style.setProperty('--blur',a.blur+'px');r.style.setProperty('--radius',a.radius+'px');r.style.setProperty('--shadow',a.shadow/100);r.style.setProperty('--motion',a.motion/70);r.style.setProperty('--cols',effectiveCols());r.style.setProperty('--row',state.grid.rowHeight+'px');r.style.setProperty('--gap',state.grid.gap+'px');$('#shade').style.opacity=a.shade/100}
function render(){
 applyAppearance();document.body.classList.toggle('editing',editing);$('#edit').textContent=editing?'完了':'編集';$('#edit').setAttribute('aria-pressed',String(editing));$('#edit-guide').hidden=!editing;$('#undo').hidden=!undoStack.length;
 const root=$('#pages');root.replaceChildren();for(const p of state.pages){const section=el('section','page');section.dataset.page=p.id;section.setAttribute('aria-label',p.name);section.inert=p.id!==state.activePage;const grid=el('div','grid');grid.dataset.page=p.id;for(const item of shownItems(p))grid.append(renderItem(item));if(!p.items.length){const add=button('ここに追加',()=>openSettings('widgets'),'empty-page');add.setAttribute('aria-label','ウィジェットやショートカットを追加');grid.append(add)}section.append(grid);root.append(section)}renderNav();renderDock();movePages(false);tick();
}
function renderItem(item){const widget=C.WIDGETS.includes(item.id),n=el('article','item '+(widget?'widget':'shortcut'));n.dataset.key=item.id;n.style.gridColumn=`${item.x+1} / span ${item.w}`;n.style.gridRow=`${item.y+1} / span ${item.h}`;n.setAttribute('aria-label',itemName(item.id));
 if(widget){const st=state.widgets[item.id].style;if(st){n.style.setProperty('--alpha',st.opacity/100);n.style.setProperty('--blur',st.blur+'px');n.style.setProperty('--radius',st.radius+'px');n.style.setProperty('--shadow',st.shadow/100);n.style.setProperty('--ink',st.text);n.style.setProperty('--muted',st.text);n.style.setProperty('--accent',st.accent)}const content=el('div','widget-content');content.dataset.widget=item.id;n.append(content);renderWidget(item.id,content)}else if(item.id.startsWith('s:')){const s=findShortcut(item.id.slice(2));if(s)n.append(appLink(s))}else{const f=findFolder(item.id.slice(2));if(f){const b=button('',()=>openFolder(f.id,n),'app-tile');const ico=el('span','app-icon folder-icon');for(const id of f.children.slice(0,9)){const s=findShortcut(id);if(!s)continue;const mini=el('span','mini',s.name[0]);mini.style.setProperty('--app-color',s.color);ico.append(mini)}b.append(ico,el('span','app-label',f.name));n.append(b)}}
 const tools=el('div','edit-tools');tools.append(actionIcon('minus','削除・非表示',()=>removeItem(item.id),'remove'),actionIcon('grip','ドラッグして移動',null,'grip'),actionIcon('edit','設定と位置',()=>configureItem(item.id),'configure'),actionIcon('resize','ドラッグしてサイズ変更',null,'resize'),el('span','size',item.w+' × '+item.h));n.append(tools);$('.grip',tools).addEventListener('pointerdown',e=>startDrag(e,item,n,false));$('.resize',tools).addEventListener('pointerdown',e=>startDrag(e,item,n,true));return n;
}
function appLink(s){const a=el('a','app-tile');a.href=s.url;a.title=s.name;a.setAttribute('aria-label',s.name);const ico=el('span','app-icon');ico.style.setProperty('--app-color',s.color);const initial=el('span','initial',s.name.slice(0,1));initial.style.color=luminance(s.color)>.55?'#244166':'#ffffff';const img=new Image();img.alt='';img.hidden=true;img.addEventListener('load',()=>img.hidden=false);img.referrerPolicy='no-referrer';img.src='https://www.google.com/s2/favicons?domain='+encodeURIComponent(new URL(s.url).hostname)+'&sz=64';img.addEventListener('error',()=>img.hidden=true);ico.append(initial,img);a.append(ico,el('span','app-label',s.name));a.addEventListener('click',e=>{if(editing){e.preventDefault();shortcutEditor(s.id)}});return a}
function renderDock(){const d=$('#dock');d.replaceChildren();for(const id of ['google','gmail','youtube','drive']){const s=findShortcut(id);if(s)d.append(appLink(s))}if(!d.childElementCount)for(const s of state.shortcuts.slice(0,4))d.append(appLink(s));d.append(el('span','dock-divider'));for(const [ic,label,fn]of [['plus','ショートカットを追加',()=>shortcutEditor()],['settings','設定',()=>openSettings()]]){const b=button('',fn,'app-tile dock-action');b.title=label;b.setAttribute('aria-label',label);const i=el('span','app-icon');i.append(icon(ic));b.append(i);d.append(b)}}
function renderNav(){const n=$('#page-nav');n.replaceChildren();state.pages.forEach((p,i)=>{const b=button('',()=>goPage(i),'page-dot');b.setAttribute('aria-label',p.name+'、'+(i+1)+'ページ');b.setAttribute('aria-current',String(p.id===state.activePage));n.append(b)})}
function movePages(animate=true,offset=0){const idx=state.pages.findIndex(p=>p.id===state.activePage),p=$('#pages');p.classList.toggle('following',!animate);p.style.transform=`translateX(calc(${-idx*100}% + ${offset}px))`;$$('.page').forEach(n=>n.inert=n.dataset.page!==state.activePage)}
function goPage(index){const i=C.clamp(index,0,state.pages.length-1);state.activePage=state.pages[i].id;persist();movePages();renderNav();$('#home').scrollTop=0}
function renderWidget(id,n){n.replaceChildren();n.className='widget-content';if(id==='clock')renderClock(n);if(id==='search')renderSearch(n);if(id==='timetable')renderTimetable(n);if(id==='weather')renderWeather(n);if(id==='gallery')renderGallery(n)}
function refreshWidget(id){$$('[data-widget="'+id+'"]').forEach(n=>renderWidget(id,n))}
function tick(){const now=new Date();$('#status-date').textContent=now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})+'　'+now.toLocaleDateString('ja-JP',{month:'short',day:'numeric',weekday:'short'});$$('[data-widget=clock]').forEach(renderClock);if(now.getSeconds()===0)refreshWidget('timetable')}
function renderClock(n){n.replaceChildren();const now=new Date(),wrap=el('div','clock-face'+(state.clock.analog?' analog':''));wrap.append(el('div','clock-date',now.toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'})));if(state.clock.analog){const face=el('div','analog-face');face.setAttribute('role','img');face.setAttribute('aria-label',now.toLocaleTimeString('ja-JP'));for(let i=0;i<12;i++){const mark=el('i','mark');mark.style.transform=`rotate(${i*30}deg)`;face.append(mark)}for(const [kind,degrees]of [['hour',now.getHours()*30+now.getMinutes()/2],['minute',now.getMinutes()*6],['second',now.getSeconds()*6]]){const h=el('i','hand '+kind);h.style.transform=`rotate(${degrees}deg)`;face.append(h)}wrap.append(face)}else{const time=el('time','clock-time');let h=now.getHours();time.textContent=String(state.clock.h24?h:(h%12||12)).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');if(!state.clock.h24)time.append(el('small','',h>=12?'PM':'AM'));wrap.append(time)}wrap.append(el('div','clock-bottom',now.getHours()<12?'おはようございます':now.getHours()<18?'こんにちは':'こんばんは'));n.append(wrap)}
function renderSearch(n){n.classList.add('search-content');const form=el('form','search-form'),input=el('input');input.id='search-input';input.type='search';input.autocomplete='off';input.placeholder='検索、またはURLを入力';input.setAttribute('aria-label','Web検索またはURL');input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls','suggestions');const submit=button('',null);submit.type='submit';submit.setAttribute('aria-label','検索');submit.append(icon('arrow'));form.append(icon('search'),input,el('span','search-hint','/'),submit);const list=el('div','suggestions');list.id='suggestions';list.role='listbox';list.hidden=true;n.append(form,list);let timer,selected=-1;
 function fill(rows){list.replaceChildren();selected=-1;for(const [idx,r]of rows.entries()){const b=button('',()=>navigateQuery(r.query,r.url),'');b.role='option';b.id='suggestion-'+idx;b.append(icon(r.url?'grid':'search'),el('span','',r.query),el('span','suggest-type',r.kind));list.append(b)}list.hidden=!rows.length;input.setAttribute('aria-expanded',String(!!rows.length));input.removeAttribute('aria-activedescendant')}
 input.addEventListener('input',()=>{clearTimeout(timer);suggestController?.abort();const q=input.value.trim();if(!q){fill([]);return}const rows=state.shortcuts.filter(s=>s.name.toLowerCase().includes(q.toLowerCase())||s.url.includes(q)).slice(0,4).map(s=>({query:s.name,url:s.url,kind:'サイト'}));if(state.search.historyEnabled)rows.push(...state.search.history.filter(h=>h.includes(q)).slice(0,3).map(query=>({query,kind:'履歴'})));fill(rows);timer=setTimeout(async()=>{suggestController=new AbortController();try{const r=await fetch('https://suggestqueries.google.com/complete/search?client=firefox&hl=ja&q='+encodeURIComponent(q),{signal:suggestController.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)return;const data=await r.json();if(input.value.trim()!==q||!input.isConnected)return;const more=Array.isArray(data[1])?data[1].filter(x=>typeof x==='string').slice(0,5).map(query=>({query,kind:'候補'})):[];fill([...rows,...more].slice(0,8))}catch{/* GitHub Pages may block Google Suggest via CORS; local results remain. */}},250)});
 input.addEventListener('keydown',e=>{const opts=$$('button',list);if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(!opts.length)return;e.preventDefault();selected=(selected+(e.key==='ArrowDown'?1:-1)+opts.length)%opts.length;opts.forEach((b,i)=>b.setAttribute('aria-selected',String(i===selected)));input.setAttribute('aria-activedescendant',opts[selected].id)}if(e.key==='Enter'&&selected>=0&&!list.hidden){e.preventDefault();opts[selected].click()}if(e.key==='Escape'){fill([]);input.blur()}});form.addEventListener('submit',e=>{e.preventDefault();navigateQuery(input.value)});input.addEventListener('blur',()=>setTimeout(()=>{if(!n.contains(document.activeElement))fill([])},150));}
function navigateQuery(q,target){q=q.trim();if(!q)return;if(state.search.historyEnabled){state.search.history=[q,...state.search.history.filter(x=>x!==q)].slice(0,30);persist()}location.assign(target||C.queryTarget(q,state.search.engine))}
function empty(n,title,description,retry){const w=el('div','empty-message');w.append(el('strong','',title),el('small','',description));if(retry)w.append(button('再試行',retry));n.append(w)}
const TIMETABLE_URL='https://johou7-275be-default-rtdb.firebaseio.com/timetable.json';
async function jsonFetch(url,timeout=12000){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{signal:ctl.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function loadTimetable(force=false){if(timetableBusy)return;const cached=readCache('newtab.timetable.cache');if(cached?.data?.schedules){timetableData=cached.data;timetableStale=Date.now()-cached.at>30*60e3;if(!force&&!timetableStale){refreshWidget('timetable');return}}timetableBusy=true;timetableError='';refreshWidget('timetable');try{const data=await jsonFetch(TIMETABLE_URL);if(!data||typeof data.schedules!=='object'||!data.schedules)throw Error('形式');timetableData=data;timetableStale=false;writeCache('newtab.timetable.cache',{at:Date.now(),data})}catch{timetableStale=!!timetableData;timetableError='時間割を取得できません。接続を確認してください。'}finally{timetableBusy=false;refreshWidget('timetable')}}
function subjectsFor(date){const day=['日曜','月曜','火曜','水曜','木曜','金曜','土曜'][date.getDay()];const v=timetableData?.schedules?.[day]?.[state.timetable.className.replaceAll('/','_')];return v&&typeof v==='object'?Array.from({length:7},(_,i)=>typeof v[i]==='string'?v[i].slice(0,80):'—'):null}
function renderTimetable(n){const now=new Date(),offset=manualDay??C.dayOffset(state.timetable,now),date=new Date(now);date.setDate(date.getDate()+offset);const times=state.timetable.preset==='custom'?state.timetable.customTimes:C.TIMES[state.timetable.preset],s=subjectsFor(date),today=subjectsFor(now),status=C.lessonStatus(times,now);if(!timetableData){empty(n,timetableBusy?'時間割を読み込み中':'時間割',timetableError||state.timetable.className+' 組の時間割を取得します。',()=>loadTimetable(true));return}
 const top=el('div','timetable-top');top.append(el('strong','widget-title',state.timetable.className+' 組'),button((offset?'明日':'今日')+' '+date.toLocaleDateString('ja-JP',{weekday:'short'}),()=>{manualDay=offset?0:1;refreshWidget('timetable')},'day-button'));n.append(top);
 let focus='今日の授業は終了しました',detail='';if(status.current>=0){focus=(today?.[status.current]||'授業中');detail='終了まで '+status.remaining+' 分'}else if(status.next>=0){focus='次は '+(today?.[status.next]||String(status.next+1)+'限');detail='開始まで '+status.remaining+' 分'}if(!today){focus='今日の時間割は未登録';detail=''}const f=el('div','lesson-focus');f.append(el('strong','',focus),el('span','remaining',detail));n.append(f);
 const tiny=el('div','timetable-tiny');tiny.append(el('small','',offset?'明日の時間割':'現在・次の授業'));if(offset){tiny.append(el('strong','',s?.find(v=>v&&v!=='—')||'登録がありません'))}else{tiny.append(el('strong','',focus),el('small','',detail),el('div','',status.current>=0&&status.next>=0?'次は '+(today?.[status.next]||String(status.next+1)+'限'):''))}n.append(tiny);
 if(s){const list=el('div','lessons');s.forEach((subject,i)=>{const row=el('div','lesson'+(!offset&&status.current===i?' current':''));row.append(el('small','',(i+1)+'限'),el('strong','',subject||'—'),el('span','lesson-time',times[i][0]));list.append(row)});n.append(list)}else n.append(el('p','note','この日の時間割は登録されていません。'));
 if(timetableStale){const note=el('div','cache-note','保存データを表示中');note.append(button('更新',()=>loadTimetable(true),'data-refresh'));n.append(note)}
}
function weatherKey(){return 'newtab.weather.'+state.weather.lat.toFixed(3)+','+state.weather.lon.toFixed(3)}
async function loadWeather(force=false){const token=++weatherRequest,key=weatherKey(),loc=C.clone(state.weather),cached=readCache(key);weatherData=cached?.data||null;weatherStale=!!cached&&Date.now()-cached.at>30*60e3;weatherError='';if(!force&&cached&&!weatherStale){refreshWidget('weather');return}weatherBusy=true;refreshWidget('weather');try{const params=new URLSearchParams({latitude:loc.lat,longitude:loc.lon,current:'temperature_2m,apparent_temperature,weather_code,is_day',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max',timezone:'auto',timeformat:'unixtime',forecast_days:'5'});const data=await jsonFetch('https://api.open-meteo.com/v1/forecast?'+params);if(!Number.isFinite(data.current?.temperature_2m)||!Array.isArray(data.hourly?.time)||!Array.isArray(data.daily?.time))throw Error('形式');if(token!==weatherRequest)return;weatherData=data;weatherStale=false;writeCache(key,{at:Date.now(),data})}catch{if(token!==weatherRequest)return;weatherStale=!!weatherData;weatherError='天気を取得できません。接続または地域設定を確認してください。'}finally{if(token===weatherRequest){weatherBusy=false;refreshWidget('weather')}}}
function weatherKind(code){if(code===0)return['晴れ','sun'];if(code<=3)return['くもり','cloud'];if(code===45||code===48)return['霧','cloud'];if([71,73,75,77,85,86].includes(code))return['雪','snow'];if(code>=95)return['雷雨','rain'];return['雨','rain']}
const temp=v=>Number.isFinite(v)?Math.round(v)+'°':'—';
function weatherContents(full=false){const d=weatherData,frag=document.createDocumentFragment(),idx=C.weatherHourIndex(d),[desc,ic]=weatherKind(d.current.weather_code);const top=el('div','weather-top',state.weather.name);const impending=d.hourly.weather_code.slice(idx+1,idx+4).findIndex(c=>c>=51);if(weatherStale)top.append(el('small','','保存データ'));else if(impending>=0)top.append(el('small','','まもなく'+(weatherKind(d.hourly.weather_code[idx+impending+1])[1]==='snow'?'雪':'雨')));frag.append(top);const main=el('div','weather-main');main.append(el('div','temperature',temp(d.current.temperature_2m)),icon(ic));frag.append(main);const line=el('div','weather-description',desc+'　'+temp(d.daily.temperature_2m_max[0])+' / '+temp(d.daily.temperature_2m_min[0]));line.append(el('small','','体感 '+temp(d.current.apparent_temperature)));frag.append(line);
 const hourly=el('div','hourly');for(let i=idx;i<Math.min(idx+6,d.hourly.time.length);i++){const h=el('div','hour');let label=new Date((d.hourly.time[i]+(d.utc_offset_seconds||0))*1000).getUTCHours()+'時';h.append(el('small','',i===idx?'現在':label),icon(weatherKind(d.hourly.weather_code[i])[1]),el('span','',temp(d.hourly.temperature_2m[i])));hourly.append(h)}frag.append(hourly);
 const details=el('div',full?'':'weather-details');details.append(el('p','note','降水確率 '+(d.hourly.precipitation_probability[idx]??'—')+'%'));const wet=d.hourly.weather_code.slice(idx+1,idx+4).findIndex(c=>c>=51);if(wet>=0)details.append(el('p','rain-note',(wet+1)+'時間以内に'+(weatherKind(d.hourly.weather_code[idx+wet+1])[1]==='snow'?'雪':'雨')+'の予報があります。'));const daily=el('div','daily');d.daily.time.slice(0,5).forEach((time,i)=>{const day=el('div','day-forecast');day.append(el('span','day-name',i===0?'今日':new Date((time+(d.utc_offset_seconds||0))*1000).toLocaleDateString('ja-JP',{weekday:'short',timeZone:'UTC'})),icon(weatherKind(d.daily.weather_code[i])[1]),el('small','',(d.daily.precipitation_probability_max[i]??'—')+'%'),el('span','day-temp',temp(d.daily.temperature_2m_min[i])+'　'+temp(d.daily.temperature_2m_max[i])));daily.append(day)});details.append(daily);frag.append(details);const credit=el('a','weather-credit','Open-Meteo'+(weatherStale?' · 保存データ':''));credit.href='https://open-meteo.com/';credit.target='_blank';credit.rel='noopener noreferrer';frag.append(credit);return frag}
function renderWeather(n){if(!weatherData){empty(n,weatherBusy?'天気を読み込み中':state.weather.name,weatherError||'最新の天気を取得します。',()=>loadWeather(true));return}n.append(weatherContents());n.append(button('',()=>{showSheet('天気');const full=el('div','weather-full');full.append(weatherContents(true));if(weatherError)full.append(el('p','note',weatherError+' 保存データを表示しています。'));full.append(button('最新の情報に更新',async()=>{await loadWeather(true);if(currentSection==='forecast'){full.replaceChildren(weatherContents(true));full.append(button('閉じる',closeSheet))}}));$('#sheet-body').append(full);currentSection='forecast'},'weather-open'));$('.weather-open',n).setAttribute('aria-label','時間ごと・5日間の予報を開く')}
function galleryURL(q,provider){if(provider==='x')return 'https://x.com/search?q='+encodeURIComponent(q+' filter:images')+'&f=live';if(provider==='google')return 'https://www.google.com/search?tbm=isch&safe=active&q='+encodeURIComponent(q);return 'https://www.pixiv.net/tags/'+encodeURIComponent(q)+'/artworks?s_mode=s_tag'}
function gallerySearch(q){q=q.trim();if(!q)return;state.gallery.recent=[q,...state.gallery.recent.filter(v=>v!==q)].slice(0,12);persist();location.assign(galleryURL(q,state.gallery.provider))}
function renderGallery(n){n.append(el('div','widget-title','イラストを探す'));const form=el('form','gallery-form'),input=el('input');input.placeholder='タグ・テーマ・作家名';input.setAttribute('aria-label','イラストの検索語');const go=button('検索',null);go.type='submit';form.append(input,go);form.addEventListener('submit',e=>{e.preventDefault();gallerySearch(input.value)});n.append(form);const chips=el('div','chips');for(const q of state.gallery.recent.slice(0,4))chips.append(button(q,()=>gallerySearch(q)));const rank=el('a','','pixivランキング');rank.href='https://www.pixiv.net/ranking.php?mode=daily&content=illust';const x=el('a','','Xの画像検索');x.href='https://x.com/search?q=illustration%20filter%3Aimages&f=live';chips.append(rank,x);n.append(chips)}
/* Placement: one shared pointer path for mouse, pen and touch. */
function activeGrid(){return $$('.grid').find(n=>n.dataset.page===state.activePage)}
function metrics(grid){const r=grid.getBoundingClientRect(),s=getComputedStyle(grid);return{r,gap:parseFloat(s.columnGap),rowGap:parseFloat(s.rowGap),cw:(r.width-(effectiveCols()-1)*parseFloat(s.columnGap))/effectiveCols(),rh:state.grid.rowHeight}}
function startDrag(e,item,node,resize){if(!editing||e.button!==0)return;e.preventDefault();e.stopPropagation();try{document.documentElement.setPointerCapture(e.pointerId)}catch{}const before=C.clone(state),grid=node.parentElement;drag={id:item.id,item:{...item},before,source:state.activePage,startX:e.clientX,startY:e.clientY,offsetX:e.clientX-node.getBoundingClientRect().left,offsetY:e.clientY-node.getBoundingClientRect().top,lastX:e.clientX,lastY:e.clientY,resize,pointer:e.pointerId,edgeTimer:null,edgeDirection:0,candidate:{...item},target:state.activePage,valid:true,folderTarget:null};node.classList.add('dragging');if(resize)node.classList.remove('dragging');drag.metrics=metrics(grid);document.body.style.userSelect='none';updateDrag(e)}
function updateDrag(e){if(!drag||e.pointerId!==drag.pointer)return;e.preventDefault();drag.lastX=e.clientX;drag.lastY=e.clientY;const grid=activeGrid(),m=metrics(grid),items=shownItems(page()),g=drag;let b;
 if(g.resize)b={...g.item,w:Math.max(1,Math.round(g.item.w+(e.clientX-g.startX)/(m.cw+m.gap))),h:Math.max(1,Math.round(g.item.h+(e.clientY-g.startY)/(m.rh+m.rowGap)))};else b={...g.item,x:Math.round((e.clientX-m.r.left-g.offsetX)/(m.cw+m.gap)),y:Math.round((e.clientY-m.r.top-g.offsetY)/(m.rh+m.rowGap))};
 b.x=Math.max(0,b.x);b.y=Math.max(0,b.y);const collisions=items.filter(i=>i.id!==g.id&&C.overlaps(i,b));g.folderTarget=!g.resize&&g.id.startsWith('s:')&&collisions.length===1&&(collisions[0].id.startsWith('s:')||collisions[0].id.startsWith('f:'))?collisions[0].id:null;g.valid=C.canPlace(items,b,effectiveCols(),g.id)||!!g.folderTarget;g.candidate=b;g.target=state.activePage;
 $$('.ghost').forEach(n=>n.remove());const ghost=el('div','ghost'+(!g.valid?' invalid':g.folderTarget?' folder-target':''),!g.valid?'重なっているため置けません':g.folderTarget?'フォルダにまとめる':'');ghost.style.left=b.x*(m.cw+m.gap)+'px';ghost.style.top=b.y*(m.rh+m.rowGap)+'px';ghost.style.width=b.w*m.cw+(b.w-1)*m.gap+'px';ghost.style.height=b.h*m.rh+(b.h-1)*m.rowGap+'px';grid.append(ghost);
 if(!g.resize){const direction=e.clientX<42?-1:e.clientX>innerWidth-42?1:0;if(direction!==g.edgeDirection){clearTimeout(g.edgeTimer);g.edgeDirection=direction;if(direction)g.edgeTimer=setTimeout(()=>crossEdge(direction),650)}const home=$('#home'),hr=home.getBoundingClientRect();if(e.clientY>hr.bottom-32)home.scrollTop+=12;else if(e.clientY<hr.top+28)home.scrollTop-=12}}
function crossEdge(direction){if(!drag)return;let index=state.pages.findIndex(p=>p.id===state.activePage)+direction;if(index<0)return;if(index>=state.pages.length){if(state.pages.length>=6){toast('ページは6枚までです。');return}state.pages.push({id:C.uid(),name:'ページ '+(state.pages.length+1),items:[]});render()}state.activePage=state.pages[index].id;movePages();renderNav();$('#home').scrollTop=0;drag.edgeDirection=0;updateDrag({pointerId:drag.pointer,clientX:drag.lastX,clientY:drag.lastY,preventDefault(){}})}
function endDrag(e,cancel=false){if(!drag||e.pointerId!==drag.pointer)return;const g=drag;clearTimeout(g.edgeTimer);try{document.documentElement.releasePointerCapture(e.pointerId)}catch{}drag=null;document.body.style.userSelect='';if(cancel||!g.valid){state=g.before;render();if(!cancel)toast('重なる位置には配置できません。');return}undoStack.push(g.before);if(undoStack.length>25)undoStack.shift();const target=state.pages.find(p=>p.id===g.target);target.items=shownItems(target);for(const p of state.pages)p.items=p.items.filter(i=>i.id!==g.id);
 if(g.folderTarget){if(g.folderTarget.startsWith('f:'))findFolder(g.folderTarget.slice(2)).children.push(g.id.slice(2));else{const targetItem=target.items.find(i=>i.id===g.folderTarget),f={id:C.uid(),name:'フォルダ',children:[g.folderTarget.slice(2),g.id.slice(2)]};state.folders.push(f);target.items=target.items.filter(i=>i.id!==g.folderTarget);target.items.push({...targetItem,id:'f:'+f.id})}toast('フォルダにまとめました。')}else target.items.push({...g.candidate,id:g.id});persist();render()}
function removeItem(id){if(C.WIDGETS.includes(id)){mutate(()=>state.widgets[id].enabled=false);toast(C.LABELS[id]+'を非表示にしました。');return}confirmAction(itemName(id)+'を削除しますか？','「元に戻す」で復元できます。',()=>{mutate(()=>{for(const p of state.pages)p.items=p.items.filter(i=>i.id!==id);if(id.startsWith('s:'))state.shortcuts=state.shortcuts.filter(s=>s.id!==id.slice(2));else{const f=findFolder(id.slice(2));state.folders=state.folders.filter(x=>x!==f);for(const sid of f?.children||[]){const pos=C.freeSpot(page().items,2,2,state.grid.columns);if(pos)page().items.push({id:'s:'+sid,...pos})}}});closeSheet()})}
function configureItem(id){if(id.startsWith('s:')){shortcutEditor(id.slice(2));return}if(id.startsWith('f:')){folderEditor(id.slice(2));return}openSettings('style:'+id)}
function positionEditor(id,parent){const found=findItem(id);if(!found)return;const section=el('div','settings-section');section.append(el('h2','','位置とサイズ'));const form=el('form','settings-card'),fields={};for(const [key,label,min,max]of [['x','列',1,effectiveCols()],['y','行',1,4096],['w','幅',1,effectiveCols()],['h','高さ',1,12]]){const i=el('input');i.type='number';i.min=min;i.max=max;i.value=found.item[key]+(['x','y'].includes(key)?1:0);i.required=true;fields[key]=i;addRow(form,label,i)}const select=el('select');for(const p of state.pages){const o=el('option','',p.name);o.value=p.id;o.selected=p.id===found.p.id;select.append(o)}addRow(form,'ページ',select);const error=el('p','form-error'),save=button('配置を変更',null,'action-button');save.type='submit';form.append(error,el('div','button-row'));$('.button-row',form).append(save);form.addEventListener('submit',e=>{e.preventDefault();const p=state.pages.find(p=>p.id===select.value),b={id,x:+fields.x.value-1,y:+fields.y.value-1,w:+fields.w.value,h:+fields.h.value},items=shownItems(p);if(!C.canPlace(items,b,effectiveCols(),id)){error.textContent='他のアイテムと重なるか、ページの範囲外です。';return}mutate(()=>{p.items=items;for(const v of state.pages)v.items=v.items.filter(i=>i.id!==id);p.items.push(b);state.activePage=p.id});toast('配置を変更しました。')});section.append(form);parent.append(section)}
/* Native modal dialogs provide focus trapping, Escape and return focus. */
function showSheet(title){const d=$('#sheet');$('#sheet-title').textContent=title;$('#sheet-body').replaceChildren();$('#sheet-back').hidden=true;currentSection=null;if(!d.open)d.showModal();$('#sheet-body').scrollTop=0}
function closeSheet(){$('#sheet').close();currentSection=null}
function confirmAction(title,message,yes){showSheet(title);const p=el('p','note',message),row=el('div','button-row');row.append(button('キャンセル',closeSheet,'action-button secondary-button'),button('実行する',yes,'action-button'));$('#sheet-body').append(p,row)}
function addRow(parent,label,control,help){const row=el('div','setting-row'),l=el('label','',label);if(control.id)l.htmlFor=control.id;else{control.id='input-'+C.uid();l.htmlFor=control.id}if(help)l.append(el('small','',help));row.append(l,control);parent.append(row);return row}
function section(parent,title){const sec=el('section','settings-section'),card=el('div','settings-card');sec.append(el('h2','',title),card);parent.append(sec);return card}
function toggle(parent,label,value,onChange,help){const i=el('input');i.type='checkbox';i.checked=value;i.addEventListener('change',()=>onChange(i.checked));addRow(parent,label,i,help);return i}
function selectRow(parent,label,value,options,onChange){const s=el('select');for(const [v,t]of options){const o=el('option','',t);o.value=v;o.selected=String(v)===String(value);s.append(o)}s.addEventListener('change',()=>onChange(s.value));addRow(parent,label,s);return s}
function range(parent,label,value,min,max,onChange,step=1){const wrap=el('div','range-controls'),i=el('input'),out=el('output','',value);i.type='range';i.min=min;i.max=max;i.step=step;i.value=value;i.setAttribute('aria-label',label);let before=null;i.addEventListener('input',()=>{if(!before)before=C.clone(state);out.value=i.value;onChange(+i.value,false)});i.addEventListener('change',()=>{if(before){undoStack.push(before);before=null}onChange(+i.value,true)});wrap.append(i,out);addRow(parent,label,wrap);return i}
function commitSetting(fn,rerender=true){checkpoint();fn();persist();if(rerender)render()}
function openSettings(sectionName='main'){showSheet('設定');currentSection=sectionName;const body=$('#sheet-body');if(sectionName!=='main'){$('#sheet-back').hidden=false;$('#sheet-back').onclick=()=>openSettings()}
 const names={appearance:'壁紙と外観',grid:'グリッドと配置',pages:'ページ',widgets:'ウィジェット',data:'データ',search:'検索',clock:'時計',timetable:'時間割',weather:'天気',gallery:'イラスト検索'};
 $('#sheet-title').textContent=names[sectionName]||(sectionName.startsWith('style:')?C.LABELS[sectionName.slice(6)]+'の外観':'設定');
 if(sectionName==='main'){const intro=el('div','settings-intro'),im=el('div','app-icon');im.append(icon('grid'));const txt=el('div');txt.append(el('h2','','NewTab'),el('p','','ホームを、自分らしく。'));intro.append(im,txt);body.append(intro);const menu=el('div','settings-menu');for(const [key,ic,desc,col]of [['appearance','image','壁紙・テーマ・ガラス','#8b68da'],['grid','grid','サイズ・配置テンプレート','#1d7fe1'],['pages','pages','追加・名前・並び順','#407dda'],['widgets','clock','表示する情報を選ぶ','#e99132'],['search','search','検索先・検索履歴','#5c77bd'],['data','data','書き出し・読み込み','#697c8b']]){const b=button('',()=>openSettings(key),'');b.style.setProperty('--menu-color',col);const tx=el('span','',names[key]);tx.append(el('small','',desc));const chevron=icon('chevron');chevron.classList.add('chevron');b.append(icon(ic),tx,chevron);menu.append(b)}body.append(menu,button('ショートカットを追加',()=>shortcutEditor(), 'action-button secondary-button'));return}
 if(sectionName==='appearance')appearanceSettings(body);
 if(sectionName==='grid')gridSettings(body);
 if(sectionName==='pages')pageSettings(body);
 if(sectionName==='widgets'){const card=section(body,'ホームに表示');for(const k of C.WIDGETS){toggle(card,C.LABELS[k],state.widgets[k].enabled,v=>{commitSetting(()=>{state.widgets[k].enabled=v;if(v&&!findItem(k)){const pos=C.freeSpot(page().items,k==='search'?6:4,k==='search'?1:3,state.grid.columns);if(pos)page().items.push({id:k,...pos})}});if(v&&k==='weather')loadWeather();if(v&&k==='timetable')loadTimetable()});const b=button(C.LABELS[k]+'の設定',()=>openSettings(k));card.append(b)}const row=el('div','button-row');row.append(button('ショートカットを追加',()=>shortcutEditor(),'action-button'));body.append(row)}
 if(sectionName==='clock'){const card=section(body,'表示');selectRow(card,'時計',state.clock.analog?'analog':'digital',[['digital','デジタル'],['analog','アナログ']],v=>commitSetting(()=>state.clock.analog=v==='analog'));toggle(card,'24時間表示',state.clock.h24,v=>commitSetting(()=>state.clock.h24=v));body.append(button('背景と文字の外観',()=>openSettings('style:clock')))}
 if(sectionName==='search'){const card=section(body,'検索');selectRow(card,'標準の検索先',state.search.engine,[['google','Google'],['bing','Bing'],['duckduckgo','DuckDuckGo'],['youtube','YouTube'],['maps','Google マップ']],v=>commitSetting(()=>state.search.engine=v));toggle(card,'検索履歴を端末に保存',state.search.historyEnabled,v=>commitSetting(()=>{state.search.historyEnabled=v;if(!v)state.search.history=[]}), '初期設定はOFF。OFFにすると保存済みの履歴も削除します。');card.append(button('検索履歴を削除',()=>{state.search.history=[];persist();toast('検索履歴を削除しました。')}));body.append(el('p','note','g / b / ddg / yt / map の後に空白と検索語を入力すると、検索先を切り替えられます。検索候補はGoogleへ入力文字を送信して取得します。通信制限がある場合も登録サイトは検索できます。'),button('背景と文字の外観',()=>openSettings('style:search')))}
 if(sectionName==='timetable')timetableSettings(body);
 if(sectionName==='weather')weatherSettings(body);
 if(sectionName==='gallery'){const card=section(body,'公式サイトで検索');selectRow(card,'検索先',state.gallery.provider,[['pixiv','pixiv'],['x','X'],['google','Google 画像']],v=>commitSetting(()=>state.gallery.provider=v));card.append(button('最近の検索語を削除',()=>{state.gallery.recent=[];persist();refreshWidget('gallery');toast('最近の検索語を削除しました。')}));body.append(el('p','note','作品画像は取得せず、各サービスの公式検索結果を開きます。Google画像はセーフ検索を有効にします。各サービスの年齢・表示制限が適用されます。'),button('背景と文字の外観',()=>openSettings('style:gallery')))}
 if(sectionName.startsWith('style:'))styleSettings(body,sectionName.slice(6));
 if(sectionName==='data')dataSettings(body);
}
function appearanceSettings(body){const card=section(body,'壁紙');const row=el('div','button-row');row.append(button('写真を選ぶ',()=>$('#wallpaper-file').click(),'action-button'),button('初期の壁紙に戻す',async()=>{try{await wallpaperStore('delete');if(wallpaperURL)URL.revokeObjectURL(wallpaperURL);wallpaperURL=null;$('#wallpaper').style.backgroundImage='';commitSetting(()=>state.appearance.palette=null);toast('初期の壁紙に戻しました。')}catch{toast('壁紙を削除できませんでした。')}},'action-button secondary-button'));card.append(row,el('p','note','JPEG・PNG・WebP、20MBまで。画像はこの端末だけに保存されます。'));range(card,'壁紙の暗さ',state.appearance.shade,0,65,(v,save)=>{state.appearance.shade=v;applyAppearance();if(save)persist()});
 const themes=section(body,'テーマ');toggle(themes,'壁紙に合わせて自動調整',state.appearance.autoTheme,v=>commitSetting(()=>state.appearance.autoTheme=v));const options=el('div','theme-options');for(const [k,name,bg]of [['silver','Silver','linear-gradient(140deg,#fcfdff,#c7dbf0)'],['ocean','Ocean','linear-gradient(140deg,#e4f8ff,#72b7db)'],['rose','Rose','linear-gradient(140deg,#fff0f6,#dfb2cb)'],['dark','Dark','linear-gradient(140deg,#40506a,#101c2e)']]){const b=button('',()=>{commitSetting(()=>{state.appearance.theme=k;state.appearance.autoTheme=false});openSettings('appearance')},'theme-option'+(!state.appearance.autoTheme&&state.appearance.theme===k?' active':''));const swatch=el('span','theme-swatch');swatch.style.background=bg;b.append(swatch,el('span','',name));options.append(b)}themes.append(options);
 const glass=section(body,'ガラス');for(const [k,name,min,max]of [['opacity','背景の不透明度',0,100],['blur','ぼかし',0,60],['radius','角丸',8,44],['shadow','影',0,60]])range(glass,name,state.appearance[k],min,max,(v,save)=>{state.appearance[k]=v;applyAppearance();if(save)persist()});const motion=section(body,'動き');range(motion,'アニメーションの強さ',state.appearance.motion,0,100,(v,save)=>{state.appearance.motion=v;applyAppearance();if(save)persist()});motion.append(el('p','note','OSの「視差効果を減らす」などの設定が優先されます。'))}
function styleSettings(body,k){const card=section(body,'個別の外観');toggle(card,'このウィジェットだけ変更',!!state.widgets[k].style,v=>{commitSetting(()=>state.widgets[k].style=v?{opacity:state.appearance.opacity,blur:state.appearance.blur,radius:state.appearance.radius,shadow:state.appearance.shadow,text:getComputedStyle(document.documentElement).getPropertyValue('--ink').trim(),accent:getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()}:null);openSettings('style:'+k)});if(state.widgets[k].style){for(const [key,name,min,max]of [['opacity','背景の不透明度',0,100],['blur','ぼかし',0,60],['radius','角丸',8,44],['shadow','影',0,60]])range(card,name,state.widgets[k].style[key],min,max,(v,save)=>{state.widgets[k].style[key]=v;render();if(save)persist()});for(const [key,name]of [['text','文字色'],['accent','アクセント色']]){const i=el('input');i.type='color';i.value=state.widgets[k].style[key];i.addEventListener('change',()=>commitSetting(()=>state.widgets[k].style[key]=i.value));addRow(card,name,i)}}body.append(el('p','note','不透明度は背景面だけに反映します。文字・数字・入力内容の濃さは変わりません。'));positionEditor(k,body)}
function gridSettings(body){const card=section(body,'グリッド');const presets=el('div','segmented');for(const [name,cols,row,gap]of [['大きめ',8,76,24],['標準',12,60,20],['細かめ',16,48,14]])presets.append(button(name,()=>{commitSetting(()=>changeGrid(cols,row,gap));openSettings('grid')}));card.append(presets);for(const [key,name,min,max]of [['columns','列数',6,16],['rowHeight','1行の高さ',40,120],['gap','間隔',8,40]])range(card,name,state.grid[key],min,max,(v,save)=>{if(save){const old=state.grid.columns;state.grid[key]=v;if(key==='columns')for(const p of state.pages)p.items=C.pack(p.items,v,old);persist();render()}});
 const layouts=section(body,'配置テンプレート');const buttons=el('div','button-row');for(const [key,name]of [['study','勉強向け'],['icons','アイコン重視'],['simple','シンプル']])buttons.append(button(name,()=>confirmAction(name+'の配置に変更しますか？','配置とウィジェットの表示を変更します。登録サイトは残ります。',()=>{mutate(()=>applyTemplate(key));openSettings('grid')}),'action-button secondary-button'));layouts.append(buttons);
 const saved=section(body,'名前を付けて保存');const form=el('form','page-row'),input=el('input');input.placeholder='配置の名前';input.maxLength=40;input.required=true;input.setAttribute('aria-label','配置の名前');const save=button('保存',null);save.type='submit';form.append(input,save);form.addEventListener('submit',e=>{e.preventDefault();if(state.layouts.length>=20){toast('保存できる配置は20件までです。');return}state.layouts.push({id:C.uid(),name:input.value.trim()||'配置',grid:C.clone(state.grid),pages:C.clone(state.pages),widgets:C.clone(state.widgets)});persist();openSettings('grid')});saved.append(form);for(const l of state.layouts){const row=el('div','layout-row');row.append(el('strong','',l.name),button('復元',()=>{mutate(()=>{const next=C.normalize({...state,grid:l.grid,pages:l.pages,activePage:l.pages[0].id,widgets:l.widgets||state.widgets});state=next});openSettings('grid')}),button('削除',()=>{commitSetting(()=>state.layouts=state.layouts.filter(v=>v.id!==l.id),false);openSettings('grid')}));saved.append(row)}}
function changeGrid(cols,row,gap){const old=state.grid.columns;state.grid={columns:cols,rowHeight:row,gap};for(const p of state.pages)p.items=C.pack(p.items,cols,old)}
function applyTemplate(kind){state.grid={columns:12,rowHeight:60,gap:20};const first={id:C.uid(),name:'ホーム',items:[]};state.pages=[first];state.activePage=first.id;for(const k of C.WIDGETS)state.widgets[k].enabled=k!=='gallery'&&(kind==='study'||k==='clock'||k==='search');const boxes=kind==='study'?[['clock',0,0,4,3],['timetable',4,0,8,3],['search',2,3,8,1],['weather',0,4,4,3]]:kind==='icons'?[['clock',0,0,4,2],['search',4,0,8,1]]:[['clock',4,0,4,3],['search',2,3,8,1]];for(const [id,x,y,w,h]of boxes)first.items.push({id,x,y,w,h});const children=new Set(state.folders.flatMap(f=>f.children));const ids=[...state.shortcuts.filter(s=>!children.has(s.id)).map(s=>'s:'+s.id),...state.folders.map(f=>'f:'+f.id)];for(const id of ids){let target=first,pos=C.freeSpot(target.items,2,2,12);if(kind==='simple'){if(state.pages.length===1)state.pages.push({id:C.uid(),name:'サイト',items:[]});target=state.pages[1];pos=C.freeSpot(target.items,2,2,12)}if(pos)target.items.push({id,...pos})}}
function pageSettings(body){const card=section(body,'ページの順序');state.pages.forEach((p,i)=>{const row=el('div','page-row'),input=el('input');input.value=p.name;input.maxLength=40;input.setAttribute('aria-label','ページ '+(i+1)+' の名前');input.addEventListener('change',()=>commitSetting(()=>p.name=input.value.trim()||'ページ'));const up=button('↑',()=>{commitSetting(()=>{[state.pages[i-1],state.pages[i]]=[state.pages[i],state.pages[i-1]]});openSettings('pages')});up.disabled=i===0;up.setAttribute('aria-label',p.name+'を前へ');const down=button('↓',()=>{commitSetting(()=>{[state.pages[i+1],state.pages[i]]=[state.pages[i],state.pages[i+1]]});openSettings('pages')});down.disabled=i===state.pages.length-1;down.setAttribute('aria-label',p.name+'を後へ');const remove=button('削除',()=>confirmAction(p.name+'を削除しますか？','アイテムは残りのページへ移します。',()=>{mutate(()=>{state.pages=state.pages.filter(v=>v.id!==p.id);const target=state.pages[0];for(const item of p.items){const pos=C.freeSpot(target.items,item.w,item.h,state.grid.columns);if(pos)target.items.push({...item,...pos})}state.activePage=target.id});openSettings('pages')}));remove.disabled=state.pages.length===1;row.append(input,up,down,remove);card.append(row)});const add=button('ページを追加',()=>{commitSetting(()=>state.pages.push({id:C.uid(),name:'ページ '+(state.pages.length+1),items:[]}));openSettings('pages')},'action-button');add.disabled=state.pages.length>=6;body.append(add,el('p','note','最大6ページ。左右スワイプ、タッチパッドの横スクロール、Shift＋ホイールでも切り替えられます。'))}
function timetableSettings(body){const card=section(body,'クラスと日付');selectRow(card,'クラス',state.timetable.className,C.CLASSES.map(v=>[v,v+' 組']),v=>{commitSetting(()=>state.timetable.className=v);manualDay=null});toggle(card,'時刻で明日の時間割に切り替える',state.timetable.autoSwitch,v=>{manualDay=null;commitSetting(()=>state.timetable.autoSwitch=v)});const time=el('input');time.type='time';time.value=state.timetable.switchTime;time.addEventListener('change',()=>{if(Number.isFinite(C.minutes(time.value))){manualDay=null;commitSetting(()=>state.timetable.switchTime=time.value)}});addRow(card,'切り替える時刻',time);
 const lessons=section(body,'授業時刻');selectRow(lessons,'授業時間',state.timetable.preset,[['50','50分授業'],['45','45分授業'],['custom','自由設定']],v=>{commitSetting(()=>state.timetable.preset=v);openSettings('timetable')});if(state.timetable.preset==='custom'){const form=el('form'),table=el('table','times-table'),head=el('tr');for(const s of ['時限','開始','終了'])head.append(el('th','',s));table.append(head);const fields=[];state.timetable.customTimes.forEach((t,i)=>{const tr=el('tr');tr.append(el('td','',(i+1)+'限'));const pair=[];for(let j=0;j<2;j++){const input=el('input');input.type='time';input.required=true;input.value=t[j];input.setAttribute('aria-label',(i+1)+'限 '+(j?'終了':'開始'));pair.push(input);const td=el('td');td.append(input);tr.append(td)}fields.push(pair);table.append(tr)});const error=el('p','form-error'),save=button('授業時刻を保存',null,'action-button');save.type='submit';form.append(table,error,save);form.addEventListener('submit',e=>{e.preventDefault();const times=fields.map(p=>p.map(v=>v.value));if(!C.validTimes(times)){error.textContent='開始は終了より前にし、前の授業と重ならない時刻を入力してください。';return}commitSetting(()=>state.timetable.customTimes=times);toast('授業時刻を保存しました。')});lessons.append(form)}body.append(button('時間割を再取得',()=>loadTimetable(true)),button('背景と文字の外観',()=>openSettings('style:timetable')))}
function weatherSettings(body){const card=section(body,'地域');card.append(el('p','note','現在の地域：'+state.weather.name));const form=el('form','page-row'),input=el('input');input.placeholder='市区町村名';input.required=true;input.setAttribute('aria-label','地域名');const go=button('検索',null);go.type='submit';const results=el('div','location-results');form.append(input,go);form.addEventListener('submit',async e=>{e.preventDefault();go.disabled=true;results.textContent='検索しています…';try{const data=await jsonFetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:input.value.trim(),count:6,language:'ja',format:'json'}));results.replaceChildren();if(!data.results?.length)results.textContent='地域が見つかりません。別の地名を入力してください。';for(const loc of data.results||[])results.append(button([loc.name,loc.admin1,loc.country].filter(Boolean).join(' · '),()=>{commitSetting(()=>state.weather={name:loc.name,lat:loc.latitude,lon:loc.longitude});loadWeather(true);openSettings('weather')}))}catch{results.textContent='地域を検索できません。接続を確認して再度検索してください。'}finally{go.disabled=false}});card.append(form,results);card.append(button('現在地を使う',()=>{if(!navigator.geolocation){toast('現在地を利用できない環境です。');return}navigator.geolocation.getCurrentPosition(p=>{commitSetting(()=>state.weather={name:'現在地',lat:p.coords.latitude,lon:p.coords.longitude});loadWeather(true);openSettings('weather')},()=>toast('現在地を取得できませんでした。地域名でも設定できます。'),{timeout:10000,maximumAge:300000})},'action-button secondary-button'));body.append(el('p','note','天気は約30分ごとに更新します。地域の座標はOpen-Meteoへ送信されます。現在地はこのボタンを押したときだけ取得します。'),button('背景と文字の外観',()=>openSettings('style:weather')))}
function dataSettings(body){const card=section(body,'バックアップ');const row=el('div','button-row');row.append(button('設定を書き出す',()=>{const data=C.clone(state);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});download(blob,'NewTab_settings.json')},'action-button'),button('設定を読み込む',()=>$('#import-file').click(),'action-button secondary-button'));card.append(row,el('p','note','配置・ショートカット・各種設定をJSONで保存します。壁紙画像は含みません。以前のNewTabの対応する設定も読み込めます。'));const reset=section(body,'初期化');reset.append(button('すべての設定を初期化',()=>confirmAction('すべての設定を初期化しますか？','配置・ショートカット・検索履歴・壁紙を削除します。必要なら先に設定を書き出してください。',async()=>{try{await wallpaperStore('delete')}catch{}state=C.defaults();undoStack=[];for(const key of ['homeGridStateV3','homeGridStateV2','pixelHomeStateV1'])try{localStorage.removeItem(key)}catch{}persist();$('#wallpaper').style.backgroundImage='';if(wallpaperURL)URL.revokeObjectURL(wallpaperURL);wallpaperURL=null;manualDay=null;render();closeSheet();loadWeather(true);loadTimetable(true);toast('初期設定に戻しました。')}),'plain danger'));body.append(el('p','note','壁紙はIndexedDB、その他の設定はこのブラウザのlocalStorageに保存します。公開ページと拡張機能は保存場所が別です。クラウド同期やアカウント登録はありません。'))}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function shortcutEditor(id){const s=id?findShortcut(id):null;showSheet(s?'ショートカットを編集':'ショートカットを追加');const body=$('#sheet-body'),form=el('form','form-stack'),fields={};for(const [key,label,type,value]of [['name','名前','text',s?.name||''],['url','URL','url',s?.url||'https://'],['color','アイコンの色','color',s?.color||'#377edb']]){const l=el('label','',label),i=el('input');i.type=type;i.value=value;i.required=true;if(key==='name')i.maxLength=40;if(key==='url')i.maxLength=2048;l.append(i);fields[key]=i;form.append(l)}const error=el('p','form-error'),save=button('保存',null,'action-button');save.type='submit';form.append(error,save);form.addEventListener('submit',e=>{e.preventDefault();const url=C.url(fields.url.value);if(!url){error.textContent='https:// または http:// のURLを入力してください。';return}const next={id:s?.id||C.uid(),name:fields.name.value.trim()||new URL(url).hostname,url,color:C.color(fields.color.value)};mutate(()=>{if(s)Object.assign(s,next);else{state.shortcuts.push(next);const pos=C.freeSpot(page().items,2,2,state.grid.columns);if(pos)page().items.push({id:'s:'+next.id,...pos})}});closeSheet();if(folderId&&$('#folder-sheet').open)renderFolder();toast('ショートカットを保存しました。')});body.append(form,el('p','note','ファビコン取得時はサイトのホスト名のみGoogleへ送信します。取得できない場合は名前の先頭文字を表示します。'));if(s){positionEditor('s:'+s.id,body);body.append(button('ショートカットを削除',()=>{if(state.folders.some(f=>f.children.includes(s.id))){confirmAction(s.name+'を削除しますか？','「元に戻す」で復元できます。',()=>{mutate(()=>{state.shortcuts=state.shortcuts.filter(v=>v.id!==s.id);for(const f of state.folders)f.children=f.children.filter(v=>v!==s.id);pruneFolders()});closeSheet();renderFolder()})}else removeItem('s:'+s.id)},'plain danger'))}}
function pruneFolders(){const empty=state.folders.filter(f=>!f.children.length).map(f=>'f:'+f.id);state.folders=state.folders.filter(f=>f.children.length);for(const p of state.pages)p.items=p.items.filter(i=>!empty.includes(i.id))}
function openFolder(id,origin){if(editing){folderEditor(id);return}folderId=id;const d=$('#folder-sheet');if(origin){const r=origin.getBoundingClientRect();d.style.setProperty('--origin',`${(r.left+r.width/2)/innerWidth*100}% ${(r.top+r.height/2)/innerHeight*100}%`)}renderFolder();if(!d.open)d.showModal()}
let folderEditing=false,folderDrag=null;
function renderFolder(){const f=findFolder(folderId);if(!f){$('#folder-sheet').close();return}$('#folder-title').textContent=f.name;const root=$('#folder-items');root.replaceChildren();for(const id of f.children){const s=findShortcut(id);if(!s)continue;const node=el('div','folder-entry');node.dataset.shortcut=id;const a=appLink(s);if(folderEditing)a.addEventListener('click',e=>{e.preventDefault();shortcutEditor(id)});node.append(a);if(folderEditing){const grip=actionIcon('grip','ドラッグで並べ替え。矢印キーでも移動できます。',null,'reorder');grip.addEventListener('pointerdown',e=>{e.preventDefault();try{document.documentElement.setPointerCapture(e.pointerId)}catch{}folderDrag={id,pointer:e.pointerId,before:C.clone(state)};node.classList.add('moving')});grip.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const i=f.children.indexOf(id),j=i+({ArrowLeft:-1,ArrowRight:1,ArrowUp:-3,ArrowDown:3}[e.key]);if(j>=0&&j<f.children.length){checkpoint();[f.children[i],f.children[j]]=[f.children[j],f.children[i]];persist();renderFolder();const focus=$$('.folder-entry').find(n=>n.dataset.shortcut===id);$('.reorder',focus)?.focus()}}});node.append(grip,button('外へ取り出す',()=>extractShortcut(f.id,id),'extract'))}root.append(node)}const actions=$('#folder-actions');actions.replaceChildren(button(folderEditing?'完了':'並べ替え・編集',()=>{folderEditing=!folderEditing;renderFolder()}),button('名前を変更',()=>folderEditor(f.id)))}
function folderEditor(id){const f=findFolder(id);if(!f)return;showSheet('フォルダを編集');const body=$('#sheet-body'),form=el('form','form-stack'),label=el('label','','フォルダ名'),input=el('input');input.value=f.name;input.maxLength=40;input.required=true;label.append(input);const save=button('保存',null,'action-button');save.type='submit';form.append(label,save);form.addEventListener('submit',e=>{e.preventDefault();commitSetting(()=>f.name=input.value.trim()||'フォルダ');closeSheet();if($('#folder-sheet').open)renderFolder()});body.append(form,button('中のショートカットを編集',()=>{closeSheet();folderId=id;folderEditing=true;renderFolder();if(!$('#folder-sheet').open)$('#folder-sheet').showModal()}));positionEditor('f:'+id,body)}
function extractShortcut(fid,id){mutate(()=>{const f=findFolder(fid);f.children=f.children.filter(v=>v!==id);const target=findItem('f:'+fid)?.p||page(),pos=C.freeSpot(target.items,2,2,state.grid.columns);if(pos)target.items.push({id:'s:'+id,...pos});pruneFolders()});renderFolder();toast('ホームへ取り出しました。')}
/* Wallpaper bytes never leave the browser. */
function luminance(hex){const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722}
function wallpaperStore(operation,value){return new Promise((resolve,reject)=>{const req=indexedDB.open('newtab.original.assets',1);req.onupgradeneeded=()=>req.result.createObjectStore('images');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,tx=db.transaction('images',operation==='get'?'readonly':'readwrite'),store=tx.objectStore('images');const request=operation==='get'?store.get('wallpaper'):operation==='delete'?store.delete('wallpaper'):store.put(value,'wallpaper');let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)}}})}
async function loadWallpaper(){try{let value=await wallpaperStore('get');if(!value){/* Migrate only the documented legacy asset store, when present. */if(indexedDB.databases){const dbs=await indexedDB.databases();if(dbs.some(d=>d.name==='home-grid-assets'))value=await new Promise(resolve=>{const req=indexedDB.open('home-grid-assets');req.onerror=()=>resolve(null);req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('wallpaper')){db.close();resolve(null);return}const tx=db.transaction('wallpaper'),r=tx.objectStore('wallpaper').get('current');r.onsuccess=()=>{const v=r.result;resolve(v instanceof Blob?{blob:v}:v?.blob instanceof Blob?{blob:v.blob}:null);db.close()};r.onerror=()=>{db.close();resolve(null)}}});if(value)await wallpaperStore('put',value)}}if(value?.blob instanceof Blob){wallpaperURL=URL.createObjectURL(value.blob);$('#wallpaper').style.backgroundImage=`url("${wallpaperURL}")`;if(value.palette){state.appearance.palette=value.palette;applyAppearance()}}}catch{toast('保存した壁紙を読み込めませんでした。初期の壁紙を表示します。')}}
async function uploadWallpaper(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024){toast('20MB以下のJPEG・PNG・WebP画像を選んでください。');return}try{const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>80e6){bitmap.close();throw Error('large')}const scale=Math.min(1,2560/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const sample=document.createElement('canvas');sample.width=32;sample.height=32;const sc=sample.getContext('2d',{willReadFrequently:true});sc.drawImage(canvas,0,0,32,32);const pixels=sc.getImageData(0,0,32,32).data;let r=0,g=0,b=0;for(let i=0;i<pixels.length;i+=4){r+=pixels[i];g+=pixels[i+1];b+=pixels[i+2]}r=Math.round(r/1024);g=Math.round(g/1024);b=Math.round(b/1024);const hex='#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join(''),bright=luminance(hex),palette={dark:bright<.35,accent:bright<.35?'#8fc8ff':bright>.72?'#215eb6':hex,label:bright>.67?'#142b43':'#ffffff'};const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.88));if(!blob)throw Error('encoding');await wallpaperStore('put',{blob,palette});if(wallpaperURL)URL.revokeObjectURL(wallpaperURL);wallpaperURL=URL.createObjectURL(blob);$('#wallpaper').style.backgroundImage=`url("${wallpaperURL}")`;commitSetting(()=>state.appearance.palette=palette);toast('壁紙を変更しました。')}catch{toast('画像を保存できませんでした。小さい画像でお試しください。')}}
/* Shell interaction and startup. */
$('#settings').append(icon('settings'));$('#settings').addEventListener('click',()=>openSettings());$('#edit').addEventListener('click',()=>{editing=!editing;render()});$('#undo').addEventListener('click',undo);
for(const d of $$('dialog')){d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});$('.close-dialog',d).addEventListener('click',()=>d.close())}
$('#folder-sheet').addEventListener('close',()=>{folderEditing=false;folderDrag=null;folderId=null});
$('#wallpaper-file').addEventListener('change',e=>{uploadWallpaper(e.target.files[0]);e.target.value=''});
$('#import-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>2*1024*1024){toast('設定ファイルは2MB以下にしてください。');return}try{const imported=C.normalize(JSON.parse(await file.text()));confirmAction('設定を読み込みますか？','現在の配置・ショートカット・設定を置き換えます。壁紙画像は変更しません。',()=>{checkpoint();const palette=state.appearance.palette;state=imported;state.appearance.palette=palette;persist();manualDay=null;render();closeSheet();loadWeather(true);loadTimetable(true);toast('設定を読み込みました。')})}catch(err){toast(err.message?.startsWith('この設定')?err.message:'設定ファイルを読み込めませんでした。JSONの形式を確認してください。')}});
document.addEventListener('pointermove',e=>{if(drag)updateDrag(e);if(folderDrag&&e.pointerId===folderDrag.pointer){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.folder-entry');if(target&&target.dataset.shortcut!==folderDrag.id){const f=findFolder(folderId),from=f.children.indexOf(folderDrag.id),to=f.children.indexOf(target.dataset.shortcut);f.children.splice(to,0,f.children.splice(from,1)[0]);renderFolder();$$('.folder-entry').find(n=>n.dataset.shortcut===folderDrag.id)?.classList.add('moving')}}},{passive:false});
document.addEventListener('pointerup',e=>{if(drag)endDrag(e);if(folderDrag&&e.pointerId===folderDrag.pointer){undoStack.push(folderDrag.before);try{document.documentElement.releasePointerCapture(e.pointerId)}catch{}folderDrag=null;persist();render();renderFolder()}});document.addEventListener('pointercancel',e=>{if(drag)endDrag(e,true);if(folderDrag){state=folderDrag.before;folderDrag=null;renderFolder()}});
const viewport=$('#viewport');viewport.addEventListener('pointerdown',e=>{if(editing||e.button!==0||e.target.closest('input,button,select,a,dialog'))return;swipe={x:e.clientX,y:e.clientY,id:e.pointerId,started:false}});viewport.addEventListener('pointermove',e=>{if(!swipe||swipe.id!==e.pointerId)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(!swipe.started&&Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>12){swipe=null;return}if(Math.abs(dx)>12){swipe.started=true;viewport.setPointerCapture(e.pointerId);movePages(false,dx*.9)}});viewport.addEventListener('pointerup',e=>{if(!swipe)return;const dx=e.clientX-swipe.x;if(swipe.started&&Math.abs(dx)>60)goPage(state.pages.findIndex(p=>p.id===state.activePage)+(dx<0?1:-1));else movePages();swipe=null});viewport.addEventListener('pointercancel',()=>{swipe=null;movePages()});
let wheel=0,wheelTimer=0,wheelLocked=false;viewport.addEventListener('wheel',e=>{if(editing||e.target.closest('.suggestions'))return;let delta=e.shiftKey?e.deltaY:e.deltaX;if(!e.shiftKey&&Math.abs(e.deltaX)<Math.abs(e.deltaY))return;if(!delta)return;e.preventDefault();if(wheelLocked)return;wheel+=delta;movePages(false,-C.clamp(wheel,-180,180));clearTimeout(wheelTimer);wheelTimer=setTimeout(()=>{if(Math.abs(wheel)>50)goPage(state.pages.findIndex(p=>p.id===state.activePage)+(wheel>0?1:-1));else movePages();wheel=0;wheelLocked=true;setTimeout(()=>wheelLocked=false,320)},100)},{passive:false});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){endDrag({pointerId:drag.pointer},true);return}if(e.target.closest('input,textarea,select')||$$('dialog[open]').length)return;if(e.key==='/'){e.preventDefault();const found=findItem('search');if(found&&state.widgets.search.enabled){goPage(state.pages.indexOf(found.p));$('#search-input')?.focus()}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){goPage(state.pages.findIndex(p=>p.id===state.activePage)+(e.key==='ArrowRight'?1:-1))}});
$('.skip-link').addEventListener('click',e=>{e.preventDefault();const found=findItem('search');if(found&&state.widgets.search.enabled){goPage(state.pages.indexOf(found.p));$('#search-input')?.focus()}else toast('検索は設定から表示できます。')});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!drag)render()},180)});
window.addEventListener('online',()=>{if(state.widgets.weather.enabled)loadWeather(true);if(state.widgets.timetable.enabled)loadTimetable(true)});
render();loadWallpaper();if(state.widgets.timetable.enabled)loadTimetable();if(state.widgets.weather.enabled)loadWeather();setInterval(tick,1000);setInterval(()=>{if(state.widgets.weather.enabled)loadWeather();if(state.widgets.timetable.enabled)loadTimetable()},30*60e3);if(bootMessage)toast(bootMessage);
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
})();
